theme: jekyll-theme-minimal
title: Patrick Hoefler
description: Blogging about.md pandas development and other stuff
show_downloads: False
navigation:
  - title: Home
    url: /
  - title: Blog
    url: blog
  - title: About
    url: about
